/***
 * Nord File Extension
 */
exports.nordFileExtMap = new Map([
    ["ncb", "Nord C2 Backup"],
    ["ncpg", "Nord C2 Program"],
    ["nc2b", "Nord C2D Backup"],
    ["nc2p", "Nord C2D Program"],
    ["neb", "Nord Electro 3 Backup"],
    ["neop", "Nord Electro 3 Organ Preset"],
    ["nepg", "Nord Electro 3 Program"],
    ["ne4o", "Nord Electro 4 Organ Preset"],
    ["ne4p", "Nord Electro 4 Program"],
    ["ne4pb", "Nord Electro 4 Program Bundle"],
    ["ne4db", "Nord Electro 4D Backup"],
    ["ne4b", "Nord Electro 4HP Backup"],
    ["ne5b", "Nord Electro 5 Backup"],
    ["ne5p", "Nord Electro 5 Program"],
    ["ne5pbundle", "Nord Electro 5 Program Bundle"],
    ["ne5t", "Nord Electro 5 Song"],
    ["ne5tbundle", "Nord Electro 5 Song Bundle"],
    ["nl4b", "Nord Lead 4 Backup"],
    ["nl4p", "Nord Lead 4 Performance"],
    ["nl4pbundle", "Nord Lead 4 Performance Bundle"],
    ["nl4s", "Nord Lead 4 Program"],
    ["nl4sbundle", "Nord Lead 4 Program Bundle"],
    ["nlab", "Nord Lead A1 Backup"],
    ["nlap", "Nord Lead A1 Performance"],
    ["nlapbundle", "Nord Lead A1 Performance Bundle"],
    ["nlas", "Nord Lead A1 Program"],
    ["nlasbundle", "Nord Lead A1 Program Bundle"],
    ["npdl", "Nord Pedal Noise"],
    ["npno", "Nord Piano"],
    ["np2b", "Nord Piano 2 Backup"],
    ["np2p", "Nord Piano 2 Program"],
    ["np2pb", "Nord Piano 2 Program Bundle"],
    ["np3b", "Nord Piano 3 Backup"],
    ["np3p", "Nord Piano 3 Program"],
    ["np3pbundle", "Nord Piano 3 Program Bundle"],
    ["npb", "Nord Piano Backup"],
    ["nppg", "Nord Piano Program"],
    ["npip", "Nord Pipe Organ"],
    ["nsmp", "Nord Sample"],
    ["nsmp3", "Nord Sample (v3)"],
    ["ns2b", "Nord Stage 2 Backup"],
    ["ns2exb", "Nord Stage 2 EX Backup"],
    ["ns2p", "Nord Stage 2 Program"],
    ["ns2pb", "Nord Stage 2 Program Bundle"],
    ["ns2s", "Nord Stage 2 Synth"],
    ["ns2synthpb", "Nord Stage 2 Synth Program Bundle"],
    ["ns3b", "Nord Stage 3 Backup"],
    ["ns3f", "Nord Stage 3 Program"],
    ["ns3fb", "Nord Stage 3 Program Bundle"],
    ["ns3s", "Nord Stage 3 Song"],
    ["ns3sbundle", "Nord Stage 3 Song Bundle"],
    ["ns3y", "Nord Stage 3 Synth"],
    ["ns3synthpb", "Nord Stage 3 Synth Bundle"],
    ["nsb", "Nord Stage Backup"],
    ["nsp", "Nord Stage Piano"],
    ["nspg", "Nord Stage Program"],
    ["nss", "Nord Stage Synth"],
    ["nwb", "Nord Wave Backup"],
    ["nwi", "Nord Wave Instrument"],
    ["nwp", "Nord Wave Program"],
]);
