/***
 * Midi Control Change
 */
const midiControlChangeMap = new Map([
    [0, "Bank Select"],
    [1, "Modulation Wheel"],
    [2, "Breath Controller"],
    [3, "Undefined"],
    [4, "Foot Controller"],
    [5, "Portamento"],
    [6, "Data Entry MSB"],
    [7, "Main Volume"],
    [8, "Balance"],
    [9, "Undefined"],
    [10, "Pan"],
    [11, "Expression"],
    [12, "Effect Control 1"],
    [13, "Effect Control 2"],
    [14, "Undefined"],
    [15, "Undefined"],
    [16, "General Purpose Controller 1"],
    [17, "General Purpose Controller 2"],
    [18, "General Purpose Controller 3"],
    [19, "General Purpose Controller 4"],
    [20, "Undefined"],
    [21, "Undefined"],
    [22, "Undefined"],
    [23, "Undefined"],
    [24, "Undefined"],
    [25, "Undefined"],
    [26, "Undefined"],
    [27, "Undefined"],
    [28, "Undefined"],
    [29, "Undefined"],
    [30, "Undefined"],
    [31, "Undefined"],
    [32, "LSB for Controller 0"],
    [33, "LSB for Controller 1"],
    [34, "LSB for Controller 2"],
    [35, "LSB for Controller 3"],
    [36, "LSB for Controller 4"],
    [37, "LSB for Controller 5"],
    [38, "LSB for Controller 6"],
    [39, "LSB for Controller 7"],
    [40, "LSB for Controller 8"],
    [41, "LSB for Controller 9"],
    [42, "LSB for Controller 10"],
    [43, "LSB for Controller 11"],
    [44, "LSB for Controller 12"],
    [45, "LSB for Controller 13"],
    [46, "LSB for Controller 14"],
    [47, "LSB for Controller 15"],
    [48, "LSB for Controller 16"],
    [49, "LSB for Controller 17"],
    [50, "LSB for Controller 18"],
    [51, "LSB for Controller 19"],
    [52, "LSB for Controller 20"],
    [53, "LSB for Controller 21"],
    [54, "LSB for Controller 22"],
    [55, "LSB for Controller 23"],
    [56, "LSB for Controller 24"],
    [57, "LSB for Controller 25"],
    [58, "LSB for Controller 26"],
    [59, "LSB for Controller 27"],
    [60, "LSB for Controller 28"],
    [61, "LSB for Controller 29"],
    [62, "LSB for Controller 30"],
    [63, "LSB for Controller 31"],
    [64, "Damper Pedal (Sustain)"],
    [65, "Portamento"],
    [66, "Sostenuto"],
    [67, "Soft Pedal"],
    [68, "Legato Footswitch"],
    [69, "Hold 2"],
    [70, "Sound Controller 1 (default: Sound Variation)"],
    [71, "Sound Controller 2 (default: Timbre/Harmonic Content)"],
    [72, "Sound Controller 3 (default: Release Time)"],
    [73, "Sound Controller 4 (default: Attack Time)"],
    [74, "Sound Controller 5 (default: Brightness)"],
    [75, "Sound Controller 6 (no defaults)"],
    [76, "Sound Controller 7 (no defaults)"],
    [77, "Sound Controller 8 (no defaults)"],
    [78, "Sound Controller 9 (no defaults)"],
    [79, "Sound Controller 10 (no defaults)"],
    [80, "General Purpose Controller 5"],
    [81, "General Purpose Controller 6"],
    [82, "General Purpose Controller 7"],
    [83, "General Purpose Controller 8"],
    [84, "Portamento Control"],
    [85, "Undefined"],
    [86, "Undefined"],
    [87, "Undefined"],
    [88, "Undefined"],
    [89, "Undefined"],
    [90, "Undefined"],
    [91, "Effects 1 Depth"],
    [92, "Effects 2 Depth"],
    [93, "Effects 3 Depth"],
    [94, "Effects 4 Depth"],
    [95, "Effects 5 Depth"],
    [96, "Data Increment"],
    [97, "Data Decrement"],
    [98, "Non-Registered Parameter Number LSB"],
    [99, "Non-Registered Parameter Number MSB"],
    [100, "Registered Parameter Number LSB"],
    [101, "Registered Parameter Number MSB"],
    [102, "Undefined"],
    [103, "Undefined"],
    [104, "Undefined"],
    [105, "Undefined"],
    [106, "Undefined"],
    [107, "Undefined"],
    [108, "Undefined"],
    [109, "Undefined"],
    [110, "Undefined"],
    [111, "Undefined"],
    [112, "Undefined"],
    [113, "Undefined"],
    [114, "Undefined"],
    [115, "Undefined"],
    [116, "Undefined"],
    [117, "Undefined"],
    [118, "Undefined"],
    [119, "Undefined"],
    [120, "All Sounds Off"],
    [121, "Reset"],
    [122, "Local Control"],
    [123, "All Notes Off"],
    [124, "Omni Off"],
    [125, "Omni On"],
    [126, "Mono On"],
    [127, "Poly On"],
]);

export { midiControlChangeMap };
