# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: build & publish 🚀

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g yarn
    - run: yarn install
    - run: yarn build
    - run: yarn test

#    - name: Push a directory to another repository
#      uses: datalbry/copy_folder_to_another_repo_action@1.0.1
#      env:
#        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
#      with:
#        source_folder: 'build'
#        destination_repo: 'chris55/nord-app'
#        destination_folder: 'build'
#        destination_branch: 'main'
#        user_email: 'christian.florentz@gmail.com'
#        user_name: 'chris55'
#        commit_msg: '[GHA] Update the build files.'

